# Introduction to NumPy
***


## What is NumPy?

NumPy is a multi-dimensional array library that uses Linear Algebra for Python.
* the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData
Ecosystem rely on NumPy.
* It has so many functions that makes implementation of machine learning easier.
***

## What are the differences between numpy arrays and python lists?

* It uses less memory.
* faster
    * Numpy does not check types when it iterates through objects unlike Python list.
    * Lists information is scattered in memory while numpy use contiguous memory allocation.


# ========================================


### Creating Arrays:

First we start off by importing NumPy:

In [1]:
import numpy as np

Initialising a one dimensional array:

In [2]:
a = np.array ([1,2,3])
a

array([1, 2, 3])

Initialising a two dimensional array:

In [3]:
b = np.array([[1.0,2.0,4.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 4.]
 [3. 4. 5.]]


In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [6]:
np.full((2,2), 11)

array([[11, 11],
       [11, 11]])

In [7]:
np.full_like(b, 7)

array([[7., 7., 7.],
       [7., 7., 7.]])

In [8]:
np.identity(6) # 2d matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Get dimensions and size of each dim:

In [10]:
print(a)
a.ndim

[1 2 3]


1

In [11]:
print(b)
b.shape

[[1. 2. 4.]
 [3. 4. 5.]]


(2, 3)

In [12]:
print(a)

[1 2 3]


In [13]:
a.shape

(3,)

In [14]:
c =np.array([[1,2,3]])
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


Get type and size:

In [15]:
a.dtype

dtype('int64')

In [16]:
b.size

6

### Slicing

In [17]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [18]:
a[1, 5]

14

In [19]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a[:, 2]

array([ 3, 11])

In [21]:
a[0, 1::2]

array([2, 4, 6, 8])

Vertically stacking vectors:

In [22]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

Horizontal stack:

In [23]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Masking:

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2!=0]

array([1, 3, 5, 7, 9])



### Random:

In [25]:
np.random.rand(4,2)#uniform distribution

array([[0.80762968, 0.04973545],
       [0.98993054, 0.95353893],
       [0.82078458, 0.10998434],
       [0.86484576, 0.2571871 ]])

In [26]:
np.random.randn(3,3)#normal distribution

array([[ 0.46331688, -1.60127125,  1.2453155 ],
       [-1.34546681,  0.23449606, -1.04288412],
       [ 0.42170579,  0.20745457, -0.56793821]])

In [27]:
np.random.randint(-4,8, size=(3,3))

array([[ 0, -2, -2],
       [ 3,  6,  2],
       [ 7, -1, -2]])

### Copying:

In [28]:
a = np.array([1,2,3])
b = a
b[0] = 5
print(a)
print(b)

[5 2 3]
[5 2 3]


In [29]:
a = np.array([1,2,3])
c = a.copy()
c[0] = 5
print(a)
print(c)

[1 2 3]
[5 2 3]


### Arithmetics:

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a + 2

array([3, 4, 5, 6])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
a * 2

array([2, 4, 6, 8])

In [34]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [36]:
c = np.ones((3,4))
a + c

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

matrix operations:

In [39]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [40]:
np.matmul(a,b)
a @ b

array([[6., 6.],
       [6., 6.]])

In [41]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [42]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [43]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.transpose(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
a = np.identity((3))
print(a)
np.linalg.det(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [46]:
stats = np.array([[1,10,3],[4,5,6]])
print(stats)

[[ 1 10  3]
 [ 4  5  6]]


In [47]:
np.min(stats)

1

In [48]:
np.max(stats, axis=1)

array([10,  6])

In [49]:
np.sum(stats, axis=1)

array([14, 15])


# =============================================


## Excercises

#### Q1 

Create a vector of ones of size 4:

In [50]:
#your code here

#### Q2

Create a vector ranging from 0 to 10:<br>(hint: you may want to use `arange()` numpy method)

In [51]:
#your code here

#### Q3

create an a vector from 1 to 5 and then add the value 9 to it:<br>(hint: you may want to use `append()` array method)

In [52]:
#your code here

#### Q4

Create a 4x3 array of random values and find the minimum, maximum and the mean of the values:

In [53]:
#your code here

#### Q5

Create a 5 x 3 matrix of even numbers between 1 and 30 (inclusive):<br>(hint: you may want to use `reshape()` array method)

In [54]:
#your code here

#### Q6

Create the following 2d array without copying it:
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
 ```

In [55]:
#your code here

# =============================================

#### This was only a brief intro to numpy.<br>There is way more things you can do with it, check the documentation at:
<br>https://docs.scipy.org/doc/numpy-1.15.0/reference/

The difference between contiguous and noncontiguous memory allocation<br>https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/