# Introduction to NumPy
***


## What is NumPy?

NumPy is a multi-dimensional array library that uses Linear Algebra for Python.
* the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData
Ecosystem rely on NumPy.
* It has so many functions that makes implementation of machine learning easier.
***

## What are the differences between numpy arrays and python lists?

* It uses less memory.
* faster
    * Numpy does not check types when it iterates through objects unlike Python list.
    * Lists information is scattered in memory while numpy use contiguous memory allocation.


# ========================================


### Creating Arrays:

First we start off by importing NumPy:

In [1]:
import numpy as np

Initialising a one dimensional array:

In [2]:
a = np.array ([1,2,3])
a

array([1, 2, 3])

Initialising a two dimensional array:

In [3]:
b = np.array([[1.0,2.0,4.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 4.]
 [3. 4. 5.]]


In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((2,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [6]:
np.full((2,2), 11)

array([[11, 11],
       [11, 11]])

In [7]:
np.full_like(b, 7)

array([[7., 7., 7.],
       [7., 7., 7.]])

In [8]:
np.identity(6) # 2d matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [9]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Get dimensions and size of each dim:

In [10]:
print(a)
a.ndim

[1 2 3]


1

In [11]:
print(b)
b.shape

[[1. 2. 4.]
 [3. 4. 5.]]


(2, 3)

In [12]:
print(a)

[1 2 3]


In [13]:
a.shape

(3,)

In [14]:
c =np.array([[1,2,3]])
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


Get type and size:

In [15]:
a.dtype

dtype('int64')

In [16]:
b.size

6

### Slicing

In [17]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [18]:
a[1, 5]

14

In [19]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
a[:, 2]

array([ 3, 11])

In [21]:
a[0, 1::2]

array([2, 4, 6, 8])

Vertically stacking vectors:

In [22]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

Horizontal stack:

In [23]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Masking:

In [24]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2!=0]

array([1, 3, 5, 7, 9])



### Random:

In [25]:
np.random.rand(4,2)#uniform distribution

array([[0.61573859, 0.14998931],
       [0.72789379, 0.34719975],
       [0.52217811, 0.25165949],
       [0.39178098, 0.28698428]])

In [26]:
np.random.randn(3,3)#normal distribution

array([[ 0.72824873, -0.94135829,  0.09306079],
       [-0.51583489, -0.59603773,  1.21803264],
       [ 1.6474038 , -0.9244213 , -0.02504864]])

In [27]:
np.random.randint(-4,8, size=(3,3))

array([[ 1,  2,  3],
       [-4, -1, -1],
       [ 6, -4, -1]])

### Copying:

In [28]:
a = np.array([1,2,3])
b = a
b[0] = 5
print(a)
print(b)

[5 2 3]
[5 2 3]


In [29]:
a = np.array([1,2,3])
c = a.copy()
c[0] = 5
print(a)
print(c)

[1 2 3]
[5 2 3]


### Arithmetics:

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a + 2

array([3, 4, 5, 6])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
a * 2

array([2, 4, 6, 8])

In [34]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [36]:
c = np.ones((3,4))
a + c

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

matrix operations:

In [39]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [40]:
np.matmul(a,b)
a @ b

array([[6., 6.],
       [6., 6.]])

In [41]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [42]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [43]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.transpose(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
a = np.identity((3))
print(a)
np.linalg.det(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [46]:
stats = np.array([[1,10,3],[4,5,6]])
print(stats)

[[ 1 10  3]
 [ 4  5  6]]


In [47]:
np.min(stats)

1

In [48]:
np.max(stats, axis=1)

array([10,  6])

In [49]:
np.sum(stats, axis=1)

array([14, 15])


# =============================================


## Excercises

#### Q1 

Create a vector of ones of size 4:

In [56]:
#your code here
np.ones(4)

array([1., 1., 1., 1.])

#### Q2

Create a vector ranging from 0 to 10:<br>(hint: you may want to use `arange()` numpy method)

In [57]:
#your code here
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Q3

create an a vector from 1 to 5 and then add the value 9 to it:<br>(hint: you may want to use `append()` array method)

In [58]:
#your code here
#any similar solution is fine
#first we create an array ranging from 1 t0 5
a = np.arange(1,6)
print(a)
#then we add 9 at the end
a = np.append(a,9)
a

[1 2 3 4 5]


array([1, 2, 3, 4, 5, 9])

#### Q4

Create a 4x3 array of random values and find the minimum, maximum and the mean of the values:

In [65]:
#your code here
#any similar solution is fine
a = np.random.random((4,3))
print(a)
print("the minimum is {}".format(a.min()))
print("the maximum is {}".format(a.max()))

[[0.38599694 0.84302856 0.59794286]
 [0.97655796 0.24570062 0.17964023]
 [0.8810424  0.32254751 0.71297154]
 [0.68433665 0.28448195 0.82249091]]
the minimum is 0.17964023211491542
the maximum is 0.9765579573852261


#### Q5

Create a 5 x 3 matrix of even numbers between 1 and 30 (inclusive):<br>(hint: you may want to use `reshape()` array method)

In [88]:
#your code here
#first we create an array ranging between 1 and 30.
a = np.arange(1,31)
#then we take the even numbers from the array using masking and reshape the array to 5x3
a = a[a%2==0].reshape(5,3)
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

#### Q6

Create the following 2d array without copying it:
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
 ```

In [84]:
#your code here
#first we create a 5x5 ones
a = np.ones((5,5))
print(a)
#then create a 3x3 zeros with 8 in the middle
b = np.zeros((3,3))
b[1,1]=8
print(b)
#now we we slice the specified values from `a` and replace them with array `b`.
a[1:-1,1:-1] = b
a

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 8., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# =============================================

#### This was only a brief intro to numpy.<br>There is way more things you can do with it, check the documentation at:
<br>https://docs.scipy.org/doc/numpy-1.15.0/reference/

The difference between contiguous and noncontiguous memory allocation<br>https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/