# Introduction to NumPy
***


## What is NumPy?

NumPy is a multi-dimensional array library that uses Linear Algebra for Python.
* the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData
Ecosystem rely on NumPy.
* It has so many functions that makes implementation of machine learning easier.
***

## What are the differences between numpy arrays and python lists?

* It uses less memory.
* faster
    * Numpy does not check types when it iterates through objects unlike Python list.
    * Lists information is scattered in memory while numpy use contiguous memory allocation.


# ========================================


### Creating Arrays:

First we start off by importing NumPy:

In [ ]:
import numpy as np

Initialising a one dimensional array:

In [ ]:
a = np.array ([1,2,3])
a

Initialising a two dimensional array:

In [ ]:
b = np.array([[1.0,2.0,4.0],[3.0,4.0,5.0]])
print(b)

In [ ]:
np.zeros((3,4))

In [ ]:
np.ones((2,2,2), dtype='int32')

In [ ]:
np.full((2,2), 11)

In [ ]:
np.full_like(b, 7)

In [ ]:
np.identity(6) # 2d matrix

In [ ]:
np.eye(6)

Get dimensions and size of each dim:

In [ ]:
print(a)
a.ndim

In [ ]:
print(b)
b.shape

In [ ]:
print(a)

In [ ]:
a.shape

In [ ]:
c =np.array([[1,2,3]])
print(c)
print(c.shape)

Get type and size:

In [ ]:
a.dtype

In [ ]:
b.size

### Slicing

In [ ]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
a

In [ ]:
a[1, 5]

In [ ]:
a[0, :]

In [ ]:
a[:, 2]

In [ ]:
a[0, -1]

In [ ]:
a[0, 1:]

In [ ]:
a[0, :-2]

In [ ]:
a[0, 1:-1:2]

Vertically stacking vectors:

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

Horizontal stack:

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

Masking:

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a>5]



### Random:

In [ ]:
np.random.rand(4,2)#uniform distribution

In [ ]:
np.random.randn(3,3)#normal distribution

In [ ]:
np.random.randint(-4,8, size=(3,3))

### Copying:

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 5
print(a)
print(b)

In [ ]:
a = np.array([1,2,3])
c = a.copy()
c[0] = 5
print(a)
print(c)

### Arithmetics:

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
c = np.ones((3,4))
a + c

In [ ]:
a ** 2

In [ ]:
np.cos(a)

matrix operations:

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

In [ ]:
np.matmul(a,b)
a @ b

In [ ]:
np.dot(a,b)

In [ ]:
a.dot(b)

In [ ]:
a.T

In [ ]:
np.transpose(a)

In [ ]:
a = np.identity((3))
print(a)
np.linalg.det(a)

In [ ]:
stats = np.array([[1,10,3],[4,5,6]])
print(stats)

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=0)

In [ ]:
np.sum(stats)


# =============================================


## Excercises

#### Q1 

Create a vector of ones of size 4:

In [ ]:
#your code here

#### Q2

Create a vector ranging from 0 to 10:<br>(hint: you may want to use `arange()` numpy method)

In [ ]:
#your code here

#### Q3

create an a vector from 1 to 5 and then add the value 9 to it:<br>(hint: you may want to use `append()` array method)

In [ ]:
#your code here

#### Q4

Create a 4x3 array of random values and find the minimum, maximum and the mean of the values:

In [ ]:
#your code here

#### Q5

Create a 5 x 3 matrix of even numbers between 1 and 30 (inclusive):<br>(hint: you may want to use `reshape()` array method)

In [ ]:
#your code here

#### Q6

Create the following 2d array without copying it:
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
 ```

In [ ]:
#your code here

# =============================================

#### This was only a brief intro to numpy.<br>There is way more things you can do with it, check the documentation at:
<br>https://docs.scipy.org/doc/numpy-1.15.0/reference/

The difference between contiguous and noncontiguous memory allocation<br>https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/