# Introduction to NumPy
***


## What is NumPy?

NumPy is a multi-dimensional array library that uses Linear Algebra for Python.
* the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData
Ecosystem rely on NumPy.
* It has so many functions that makes implementation of machine learning easier.
***

## What are the differences between numpy arrays and python lists?

* It uses less memory.
* faster
    * Numpy does not check types when it iterates through objects unlike Python list.
    * Lists information is scattered in memory while numpy use contiguous memory.


# ========================================


#### Creating Arrays

First we start off by importing NumPy:

In [85]:
import numpy as np

Initialising a one dimensional array:

In [87]:
a = np.array ([1,2,3])
a

array([1, 2, 3])

Initialising a two dimensional array:

In [88]:
b = np.array([[1.0,2.0,4.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 4.]
 [3. 4. 5.]]


In [90]:
np.zeros(3)

array([0., 0., 0.])

In [91]:
np.ones((2,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [92]:
np.full((2,2), 11)

array([[11, 11],
       [11, 11]])

In [93]:
np.full_like(b, 7)

array([[7., 7., 7.],
       [7., 7., 7.]])

In [96]:
np.identity(6) # 2d matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Get dimensions and size of each dim:

In [97]:
a.ndim

1

In [101]:
print(a)
a.shape
c =np.array([[1,2,3]])
print(c)
print(c.shape)

[1 2 3]
[[1 2 3]]
(1, 3)


In [103]:
print(b)
b.shape

[[1. 2. 4.]
 [3. 4. 5.]]


(2, 3)

Get type and size:

In [104]:
a.dtype

dtype('int64')

In [106]:
b.size

6

In [111]:
#a.itemsize

8

In [ ]:
#a.nbytes

#### Slicing

In [112]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [113]:
a[1, 5]

13

In [114]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [115]:
a[:, 2]

array([ 3, 10])

In [116]:
a[0, 1:-1:2]

array([2, 4, 6])

In [117]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 8
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 8. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Vertically stacking vectors:

In [119]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

Horizontal stack:

In [120]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Masking:

In [128]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a>5]

array([ 6,  7,  8,  9, 10])



### Random:

In [129]:
np.random.rand(4,2)

array([[0.50336715, 0.66169302],
       [0.3623666 , 0.57453348],
       [0.3245997 , 0.23906344],
       [0.81611496, 0.10483017]])

In [133]:
np.random.randint(-4,8, size=(3,3))

array([[ 4, -3,  4],
       [ 0,  4,  1],
       [ 2, -3,  3]])

### Copying:

In [134]:
a = np.array([1,2,3])
b = a
b[0] = 5
print(a)
print(b)

[5 2 3]
[5 2 3]


In [135]:
a = np.array([1,2,3])
c = a.copy()
c[0] = 5
print(a)
print(c)

[1 2 3]
[5 2 3]


### Arithmetics:

In [136]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [137]:
a + 2

array([3, 4, 5, 6])

In [138]:
a - 2

array([-1,  0,  1,  2])

In [139]:
a * 2

array([2, 4, 6, 8])

In [140]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [141]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
#example of adding 2d array to 1d

In [142]:
a ** 2

array([ 1,  4,  9, 16])

In [143]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

matrix operations:

In [144]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [145]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [146]:
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [147]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [148]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [149]:
np.transpose(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [151]:
a = np.identity((3))
print(a)
np.linalg.det(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [155]:
stats = np.array([[1,10,3],[4,5,6]])
print(stats)

[[ 1 10  3]
 [ 4  5  6]]


In [153]:
np.min(stats)

1

In [157]:
np.max(stats, axis=0)

array([ 4, 10,  6])

In [159]:
np.sum(stats, axis=1)

array([14, 15])


# =============================================


## Excercises

#### Q1 

Create a vector of ones of size 4:

In [ ]:
#your code here

#### Q2

Create a vector ranging from 0 to 10:<br>(hint: you may want to use `arange()` numpy method)

In [ ]:
#your code here

#### Q3

create an a vector from 1 to 5 and then add the value 9 to it:<br>(hint: you may want to use `append()` array method)

In [ ]:
#your code here

#### Q4

Create a 4x3 array of random values and find the minimum, maximum and the mean of the values:

In [ ]:
#your code here

#### Q5

Create a 5 x 3 matrix of even numbers between 1 and 30 (inclusive):<br>(hint: you may want to use `reshape()` array method)

In [ ]:
#your code here

#### Q6

Create the following 2d array without copying it:

In [ ]:
#your code here

#### This was only a brief intro to numpy.<br>There is way more things you can do with it, check the documentation at:
<br>https://docs.scipy.org/doc/numpy-1.15.0/reference/