# Introduction to NumPy
***


## What is NumPy?

NumPy is a multi-dimensional array library that uses Linear Algebra for Python.
* the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData
Ecosystem rely on NumPy.
* It has so many functions that makes implementation of machine learning easier.
***

## What are the differences between numpy arrays and python lists?

* It uses less memory.
* faster
    * Numpy does not check types when it iterates through objects unlike Python list.
    * Lists information is scattered in memory while numpy use contiguous memory allocation.


# ========================================


### Creating Arrays:

First we start off by importing NumPy:

In [1]:
import numpy as np

Initialising a one dimensional array:

In [ ]:
a = np.array ([1,2,3])
a

Initialising a two dimensional array:

In [ ]:
b = np.array([[1.0,2.0,4.0],[3.0,4.0,5.0]])
print(b)

In [ ]:
np.zeros(3)

In [ ]:
np.ones((2,2,2), dtype='int32')

In [ ]:
np.full((2,2), 11)

In [ ]:
np.full_like(b, 7)

In [ ]:
np.identity(6) # 2d matrix

In [3]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Get dimensions and size of each dim:

In [4]:
print(a)
a.ndim

NameError: name 'a' is not defined

In [5]:
print(b)
b.shape

NameError: name 'b' is not defined

In [ ]:
print(a)

In [ ]:
a.shape

In [ ]:
c =np.array([[1,2,3]])
print(c)
print(c.shape)

Get type and size:

In [ ]:
a.dtype

In [ ]:
b.size

### Slicing

In [ ]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
a

In [ ]:
a[1, 5]

In [ ]:
a[0, :]

In [ ]:
a[:, 2]

In [ ]:
a[0, 1:-1:2]

In [ ]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 8
print(z)
output[1:-1,1:-1] = z
print(output)

Vertically stacking vectors:

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

Horizontal stack:

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

Masking:

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a>5]



### Random:

In [6]:
np.random.rand(4,2)#uniform distribution

array([[0.28314504, 0.81659389],
       [0.07568522, 0.21257577],
       [0.49065108, 0.46904263],
       [0.66614127, 0.65844289]])

In [12]:
np.random.randn(3,3)#normal distribution

array([[ 1.62940247,  0.6356334 ,  1.60626555],
       [ 0.60978099, -1.21653484, -0.20127852],
       [-0.30260501,  0.66736206,  1.27633862]])

In [ ]:
np.random.randint(-4,8, size=(3,3))

### Copying:

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 5
print(a)
print(b)

In [ ]:
a = np.array([1,2,3])
c = a.copy()
c[0] = 5
print(a)
print(c)

### Arithmetics:

In [15]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [20]:
c = np.ones((3,4))
a + c

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [ ]:
a ** 2

In [ ]:
np.cos(a)

matrix operations:

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

In [ ]:
np.matmul(a,b)

In [ ]:
np.dot(a,b)

In [ ]:
a.dot(b)

In [ ]:
a.T

In [ ]:
np.transpose(a)

In [ ]:
a = np.identity((3))
print(a)
np.linalg.det(a)

In [ ]:
stats = np.array([[1,10,3],[4,5,6]])
print(stats)

In [ ]:
np.min(stats)

In [ ]:
np.max(stats, axis=0)

In [ ]:
np.sum(stats, axis=1)


# =============================================


## Excercises

#### Q1 

Create a vector of ones of size 4:

In [ ]:
#your code here

#### Q2

Create a vector ranging from 0 to 10:<br>(hint: you may want to use `arange()` numpy method)

In [ ]:
#your code here

#### Q3

create an a vector from 1 to 5 and then add the value 9 to it:<br>(hint: you may want to use `append()` array method)

In [ ]:
#your code here

#### Q4

Create a 4x3 array of random values and find the minimum, maximum and the mean of the values:

In [ ]:
#your code here

#### Q5

Create a 5 x 3 matrix of even numbers between 1 and 30 (inclusive):<br>(hint: you may want to use `reshape()` array method)

In [ ]:
#your code here

#### Q6

Create the following 2d array without copying it:
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 8. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
 ```

In [ ]:
#your code here

# =============================================

#### This was only a brief intro to numpy.<br>There is way more things you can do with it, check the documentation at:
<br>https://docs.scipy.org/doc/numpy-1.15.0/reference/

The difference between contiguous and noncontiguous memory allocation<br>https://www.geeksforgeeks.org/difference-between-contiguous-and-noncontiguous-memory-allocation/